require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.harpoon"
require "user.lualine"
require "user.toggleterm"
require "user.impatient"
require "user.illuminate"
require "user.indentline"
require "user.lsp"
require "user.lsp_signature"
require "user.header42"
require "user.autosave"
require "user.luasnip"
require "user.which-key"
-- require "user.vm-multi"
-- require "user.bufferline"
-- require "user.project"
-- require "user.alpha"
-- require "user.dap"
